from collections.abc import Iterable

import pytest

from ragkit.keyword.bm25_searcher import BM25Searcher
from ragkit.llms.llm import LLM
from ragkit.models.llm_response import LLMResponse
from ragkit.models.search_result import SearchResult
from ragkit.prompts.prompt_builder import PromptBuilder
from ragkit.ranking.reciprocal_rank_fusion import ReciprocalRankFusion
from ragkit.retrievers.retriever import Retriever
from ragkit.services.rag_service import RAGService


class FakeRetriever(Retriever):
    """
    Fake semantic retriever used for testing.
    """

    def __init__(self) -> None:
        self.last_query = None
        self.last_top_k = None
        self.last_filters = None

    def retrieve(
        self,
        query: str,
        top_k: int = 5,
        filters: dict | None = None,
    ) -> Iterable[SearchResult]:
        self.last_query = query
        self.last_top_k = top_k
        self.last_filters = filters

        return []


class FakeBM25Searcher:
    """
    Fake BM25 searcher used for testing.
    """

    def __init__(self) -> None:
        self.last_query = None
        self.last_top_k = None
        self.last_document_ids = None

    def search(
        self,
        query: str,
        top_k: int = 5,
        document_ids=None,
    ) -> Iterable[SearchResult]:
        self.last_query = query
        self.last_top_k = top_k
        self.last_document_ids = document_ids

        return []


class FakeRRF:
    """
    Fake Reciprocal Rank Fusion used for testing.
    """

    def __init__(self) -> None:
        self.last_results = None
        self.last_top_k = None

    def fuse(
        self,
        result_lists: list[Iterable[SearchResult]],
        top_k: int = 5,
    ) -> list[SearchResult]:
        self.last_results = result_lists
        self.last_top_k = top_k

        return []


class FakePromptBuilder:
    """
    Fake PromptBuilder used for testing.
    """

    def __init__(self) -> None:
        self.last_query = None
        self.last_results = None

    def build(
        self,
        *,
        query: str,
        search_results: Iterable[SearchResult],
    ) -> str:
        self.last_query = query
        self.last_results = search_results

        return "TEST PROMPT"


class FakeLLM:
    """
    Fake LLM used for testing.
    """

    def __init__(self) -> None:
        self.last_prompt = None

    def generate(
        self,
        *,
        prompt: str,
    ) -> LLMResponse:
        self.last_prompt = prompt

        return LLMResponse(
            content="TEST ANSWER",
        )


def create_service(
    top_k: int = 5,
):
    """
    Create RAGService with fake dependencies.
    """

    retriever = FakeRetriever()
    keyword_searcher = FakeBM25Searcher()
    rrf = FakeRRF()
    prompt_builder = FakePromptBuilder()
    llm = FakeLLM()

    service = RAGService(
        retriever=retriever,
        keyword_searcher=keyword_searcher,
        rrf=rrf,
        prompt_builder=prompt_builder,
        llm=llm,
        top_k=top_k,
    )

    return (
        service,
        retriever,
        keyword_searcher,
        rrf,
        prompt_builder,
        llm,
    )


def test_rag_service_returns_llm_response():
    """
    Verify RAGService returns the response generated by the LLM.
    """

    (
        service,
        _,
        _,
        _,
        _,
        llm,
    ) = create_service()

    response = service.ask(
        "How many years of experience?",
    )

    assert isinstance(response, LLMResponse)
    assert response.content == "TEST ANSWER"
    assert llm.last_prompt == "TEST PROMPT"


def test_rag_service_passes_query_to_retrievers():
    """
    Verify the user's query is passed to both retrieval strategies.
    """

    (
        service,
        retriever,
        keyword_searcher,
        _,
        _,
        _,
    ) = create_service()

    service.ask(
        "How many years of experience?",
    )

    assert retriever.last_query == "How many years of experience?"
    assert keyword_searcher.last_query == "How many years of experience?"


def test_rag_service_passes_top_k():
    """
    Verify top_k is passed to all retrieval stages.
    """

    (
        service,
        retriever,
        keyword_searcher,
        rrf,
        _,
        _,
    ) = create_service(
        top_k=10,
    )

    service.ask(
        "How many years of experience?",
    )

    assert retriever.last_top_k == 10
    assert keyword_searcher.last_top_k == 10
    assert rrf.last_top_k == 10


def test_rag_service_passes_filters_to_retriever():
    """
    Verify metadata filters are forwarded to semantic retrieval.
    """

    (
        service,
        retriever,
        _,
        _,
        _,
        _,
    ) = create_service()

    filters = {
        "author": "Yogesh",
    }

    service.ask(
        "How many years of experience?",
        filters=filters,
    )

    assert retriever.last_filters == filters


def test_rag_service_passes_results_to_rrf():
    """
    Verify vector and BM25 results are passed to RRF.
    """

    (
        service,
        retriever,
        keyword_searcher,
        rrf,
        _,
        _,
    ) = create_service()

    service.ask(
        "Apache Spark",
    )

    assert rrf.last_results is not None
    assert len(rrf.last_results) == 2


def test_rag_service_builds_prompt_from_rrf_results():
    """
    Verify the RRF results are passed to PromptBuilder.
    """

    (
        service,
        _,
        _,
        _,
        prompt_builder,
        _,
    ) = create_service()

    service.ask(
        "Apache Spark",
    )

    assert prompt_builder.last_query == "Apache Spark"
    assert prompt_builder.last_results is not None


def test_rag_service_rejects_empty_query():
    """
    Verify empty queries are rejected.
    """

    (
        service,
        _,
        _,
        _,
        _,
        _,
    ) = create_service()

    with pytest.raises(ValueError):
        service.ask("")


def test_rag_service_rejects_whitespace_query():
    """
    Verify whitespace-only queries are rejected.
    """

    (
        service,
        _,
        _,
        _,
        _,
        _,
    ) = create_service()

    with pytest.raises(ValueError):
        service.ask("   ")


def test_rag_service_rejects_invalid_top_k():
    """
    Verify top_k must be greater than zero.
    """

    with pytest.raises(ValueError):
        create_service(
            top_k=0,
        )

def test_rag_service_passes_document_ids_to_bm25():
    """
    Verify selected document IDs are forwarded
    to BM25 search.
    """

    from uuid import uuid4

    (
        service,
        _,
        keyword_searcher,
        _,
        _,
        _,
    ) = create_service()

    document_ids = [
        uuid4(),
        uuid4(),
    ]

    service.ask(
        "Apache Spark",
        document_ids=document_ids,
    )

    assert keyword_searcher.last_document_ids == document_ids



